-- SQL script to create the vocabulary_bank table in Supabase.
-- Paste this script into the SQL Editor in your Supabase Dashboard:
-- https://supabase.com/dashboard/project/pvzlawprdqoofjgxwfbd/sql/new

CREATE TABLE public.vocabulary_bank (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word TEXT NOT NULL UNIQUE,
    pos TEXT NOT NULL,          -- part of speech (noun, verb, adjective, adverb, phrase)
    register TEXT NOT NULL DEFAULT 'academic',
    definition TEXT,
    example_sentence TEXT,
    domain TEXT DEFAULT 'general',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.vocabulary_bank ENABLE ROW LEVEL SECURITY;

-- Allow public read access (necessary for any user queries)
CREATE POLICY "Allow public read access" ON public.vocabulary_bank
    FOR SELECT USING (true);

-- Allow service role write access (necessary for the backend to insert/delete words)
CREATE POLICY "Allow service role write access" ON public.vocabulary_bank
    FOR ALL TO service_role USING (true) WITH CHECK (true);
